### ISSUE TITLE
3  errors

### ISSUE THREAD

**Issue by Theo-denBlanken** [Minoord/Ontwerp-L1P2-#2]
bij validatie

**Comment by Minoord** [comment]
Als het  goed is moet er nu geen errors er meer uit komen.

**Comment by Theo-denBlanken** [comment]
De validator blijft ze zien. Er is hier wel een update, maar heb de de verbetering ook naar hosts.ma-cloud geüpload?

**Comment by Minoord** [comment]
> De validator blijft ze zien. Er is hier wel een update, maar heb de de verbetering ook naar hosts.ma-cloud geüpload?

Ik was vergeten de links te updaten als het goed is krijgt u nu geen errors meer
